openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'feed-store'
  license:
    name: MIT
servers:
  - url: 'localhost:48000'
paths:
  /feed:
    get:
      summary: 'Gets all feeds meta data'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    FeedList:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
     
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []